workload:
  model:
    type: resnet50
    accuracy_function: classification_accuracy
    weights: null

  calibration:
    samples: null # null sets samples to all
    datasets:
      calibrate:
        type: imagenet
        kind: 'imagefolder'
        path: '/tools/datasets/imagenet/val_images'
        sample_limit: null # number of validation dataset samples to test for each individual
        batch_size: 512

  exploration:
    nsga: # Setup the parameters for your nsga algorithm
      pop_size: 20
      offsprings: 20
      generations: 25
      mutation_eta: 20
      mutation_prob: 0.9
      crossover_eta: 15
      crossover_prob: 0.9
    minimum_accuracy: 0.72 # accuracy constraint
    bit_widths: [2, 16]
    bit_weighting_function: 'bits_weighted_per_layer'
    datasets:
      exploration:
        type: imagenet
        kind: 'imagefolder'
        path: '/tools/datasets/imagenet/val_images'
        sample_limit: 8196 # number of validation dataset samples to test for each individual
        batch_size: 512
      baseline:
        type: imagenet
        kind: 'imagefolder'
        path: '/tools/datasets/imagenet/val_images'
        sample_limit: null
        batch_size: 512

  retraining:
    epochs: 2
    datasets:
      validation:
        type: imagenet
        kind: 'imagefolder'
        path: '/tools/datasets/imagenet/val_images'
        sample_limit: 8192 # number of validation dataset samples to test for each individual
        batch_size: 512
      train:
        type: imagenet
        kind: 'webdataset'
        path: '/tools/datasets/imagenet/train/imagenet-train-{0000..0136}.tar'
        total_samples: 1281167
        batch_size: 512
        sample_limit: null

