workload:
  dataset:
    path: '/tools/datasets/imagenet/val_images'
    type: imagenet
  model:
    type: resnet18
    accuracy_function: classification_accuracy
    weights: null

  calibration:
    samples: null # null sets samples to all
  exploration:
    nsga: # Setup the parameters for your nsga algorithm
        pop_size: 12
        offsprings: 12
        generations: 20
        mutation_eta: 20
        mutation_prob: 0.9
        crossover_eta: 15
        crossover_prob: 0.9
    minimum_accuracy: 0.7 # accuracy contraint
    sample_limit: 8192 # number of validation dataset samples to test for each individual
    batch_size: 512
  retraining:
    samples: null

