workload:
  problem:
    problem_function: sparsity_problem
    # problem_function: quantization_problem

  model:
    type: yolov5s
    accuracy_function: detection_accuracy
    weights: null

  calibration:
    samples: null # null sets samples to all
    file: './results/resnet50_quant_calib.pkl'
    datasets:
      calibrate:
        type: yolo_dataset
        kind: 'imagefolder'
        path: '/hkfs/work/workspace_haic/scratch/oq4116-datasets/coco/images/val2017'
        groundtruth: '/hkfs/work/workspace_haic/scratch/oq4116-datasets/coco/annotations/instances_val2017.json'
        sample_limit: null # number of validation dataset samples to test for each individual
        batch_size: 512

  exploration:
    nsga: # Setup the parameters for your nsga algorithm
      pop_size: 10
      offsprings: 10
      generations: 20
      mutation_eta: 20
      mutation_prob: 0.9
      crossover_eta: 30
      crossover_prob: 0.7
    minimum_accuracy: 0.80 # accuracy constraint
    datasets:
      exploration:
        type: imagenet
        kind: 'imagefolder'
        path: '/hkfs/work/workspace_haic/scratch/oq4116-datasets/val_images'
        sample_limit: 4096 # number of validation dataset samples to test for each individual
        batch_size: 512
      baseline:
        type: imagenet
        kind: 'imagefolder'
        path: '/hkfs/work/workspace_haic/scratch/oq4116-datasets/val_images'
        sample_limit: null
        batch_size: 512
    extra_args:
      # for quantization
      num_bits_upper_limit: 16
      num_bits_lower_limit: 2
      bit_weighting_function: 'bits_weighted_per_layer'
      # for sparsity
      discrete_threshold_steps: 100
      discrete_threshold_method: linear
      threshold_limit: 0.8
      block_size: [8,8]

  retraining:
    epochs: 4
    datasets:
      validation:
        type: imagenet
        kind: 'imagefolder'
        path: '/hkfs/work/workspace_haic/scratch/oq4116-datasets/val_images'
        sample_limit: 8192 # number of validation dataset samples to test for each individual
        batch_size: 256
      train:
        type: imagenet
        kind: 'webdataset'
        path: '/tools/datasets/imagenet/train/imagenet-train-{0000..0136}.tar'
        total_samples: 1281167
        batch_size: 256
        sample_limit: null

  reevaluation:
    bit_weighting_function: 'bits_weighted_per_layer'
    datasets:
      reevaluate:
        type: imagenet
        kind: 'imagefolder'
        path: '/hkfs/work/workspace_haic/scratch/oq4116-datasets/val_images'
        sample_limit: null
        batch_size: 512


